import type { Metadata } from "next";
import { Kumbh_Sans as KumbhSans } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar/Navbar";

const kumbh = KumbhSans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={kumbh.className}>
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
